src/api/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from .views import CreatePostView,PostDetailsView,PlaceDetailsView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = {
    url(r'^api/create$', CreatePostView.as_view(), name="create_post"),
    url(r'^api/post/(?P<pk>[0-9]+)$',PostDetailsView.as_view(), name="post_details"),
    url(r'^api/place/(?P<pk>[0-9]+)$',PlaceDetailsView.as_view(), name="place_details"),
    url(r'^api/get-token/', obtain_auth_token),
}

urlpatterns = format_suffix_patterns(urlpatterns)

src/config/dev/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from users.views import home,instagram,terms,facebook,comingsoon,email,success,about
from blog.views import post_list, post_detail, blogger_detail, blogger_list

urlpatterns = [
    url(r'^$',home, name='home'),
    url(r'^posts/$',post_list, name='post_list'),
    url(r'^posts/(?P<slug>[-\w\d]+)$',post_detail,name='post_detail'),
    url(r'^bloggers/$',blogger_list, name='blogger_list'),
    url(r'^bloggers/(?P<id>\d+)$',blogger_detail,name='blogger_detail'),
    #url(r'^contact/$', contact, name='contact'),
    url(r'^contact/$', email, name='contact'),
    url(r'^about/$',about, name='about'),
    url(r'^success/$', success, name='success'),
    #url(r'^instaposts/$', instagram, name='instagram_posts'),
    url(r'^fbposts/$', facebook, name='facebook_posts'),
    url(r'^tos/$', terms, name='terms_and_conditions'),
    url(r'^comingsoon/$', comingsoon, name='comingsoon'),
    #url(r'^posts/', include('blog.urls',namespace='posts')),
    url(r'^places/', include('tourism.urls',namespace='places')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('api.urls')),
]

handler404 = 'users.views.urlnotfound'
handler500 = 'users.views.servererror'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/config/prod/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from users.views import home,instagram,terms,facebook,comingsoon,email,success,about
from blog.views import post_list, post_detail,blogger_detail,blogger_list

urlpatterns = [
    url(r'^$',home, name='home'),
    url(r'^posts/$',post_list, name='post_list'),
    url(r'^posts/(?P<slug>[-\w\d]+)$',post_detail,name='post_detail'),
    url(r'^bloggers/$',blogger_list, name='blogger_list'),
    url(r'^bloggers/(?P<id>\d+)$',blogger_detail,name='blogger_detail'),
    #url(r'^contact/$', contact, name='contact'),
    url(r'^contact/$', email, name='contact'),
    url(r'^about/$',about, name='about'),
    url(r'^success/$', success, name='success'),
    #url(r'^instaposts/$', instagram, name='instagram_posts'),
    url(r'^fbposts/$', facebook, name='facebook_posts'),
    url(r'^tos/$', terms, name='terms_and_conditions'),
    url(r'^comingsoon/$', comingsoon, name='comingsoon'),
    #url(r'^posts/', include('blog.urls',namespace='posts')),
    url(r'^places/', include('tourism.urls',namespace='places')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('api.urls')),
]

handler404 = 'users.views.urlnotfound'
handler500 = 'users.views.servererror'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tourism/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from .views import district_places, place_detail, place_spots, spot_detail, temple_detail


urlpatterns = [
    url(r'^district/(?P<slug>[-\w\d]+)$',district_places, name='district_places'),
    url(r'^(?P<slug>[-\w\d]+)$', view=place_detail, name='place_detail'),
    url(r'^spots/(?P<slug>[-\w\d]+)$', view=place_spots, name='place_spots'),
    url(r'^spot/(?P<slug>[-\w\d]+)$', view=spot_detail, name='spot_detail'),
    url(r'^temple/(?P<slug>[-\w\d]+)$', view=temple_detail, name='temple_detail'),
    ]

#url(r'^places/', include('tourism.urls',namespace='places')),

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>{% block head_title %}Uttarakhand Traveller{% endblock %}</title>

    {% include 'head_css.html' %}

    

    {% block style %}
    {% endblock %}
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
         (adsbygoogle = window.adsbygoogle || []).push({
         google_ad_client: "ca-pub-5697792530730507",
         enable_page_level_ads: true
     });
    </script>

  </head>

  <body>

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <div ></div>
  {% include 'navbar.html' %}
  <br/><br/><br/>
  {% block container %}
  {% endblock %}

  {% block jumbotron %}

  {% endblock %}

  {% block content %}


  {% endblock %}


  {% include "javascript.html" %}
  <script type="text/javascript">
</script>
  </body>
</html>

src/templates/comingsoon.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<title>{{ title }} | Uttarakhand Traveller </title>

<style>
body, html {
    height: 100%;
    margin: 0;
}

.bgimg {
    background-image: url('https://www.w3schools.com/w3images/forestbridge.jpg');
    height: 100%;
    background-position: center;
    background-size: cover;
    position: relative;
    color: white;
    font-family: "Courier New", Courier, monospace;
    font-size: 25px;
}

.topleft {
    position: absolute;
    top: 0;
    left: 16px;
}

.bottomleft {
    position: absolute;
    bottom: 0;
    left: 16px;
}

.middle {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    text-align: center;
}

hr {
    margin: auto;
    width: 40%;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 50%;
}
</style>
<body>
<div class="bgimg">
  <div class="topleft">
    <img  src="{% static 'img/logo.jpg' %}" class="img-rounded" height="120"/>
  </div>
  <div class="middle">
    <h1>COMING SOON</h1>
    <hr>
    <p id="demo" style="font-size:30px"></p>
    <a href="http://www.uttarakhandtraveller.com"><button>Go back</button></a>
  </div>
  
</div>

<script>
// Set the date we're counting down to
var countDownDate = new Date("Jan 5, 2018 15:37:25").getTime();

// Update the count down every 1 second
var countdownfunction = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();
    
    // Find the distance between now an the count down date
    var distance = countDownDate - now;
    
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
    // Output the result in an element with id="demo"
    document.getElementById("demo").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";
    
    // If the count down is over, write some text 
    if (distance < 0) {
        clearInterval(countdownfunction);
        document.getElementById("demo").innerHTML = "EXPIRED";
    }
}, 1000);
</script>
</body>
</html>

src/templates/facebook.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block head_title %}{{ title }} | {{ block.super }}{% endblock %}

{% block style %}

{% include 'post_style.html' %}
{% endblock %}

{% block container %}

 <div class="container">
  <h1>Recent Facebook Posts</h1>
    <div class="row">
    {% for post in facebookposts %}
        <div class="col-md-6">
            <div class="bluebox">
                <img src="{{ post.image }}" class="img-responsive"/>
                <p>{{ post.text|linebreaks  }}</p>
            </div>
        </div>
    {% endfor %}
     </div>
</div>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
     google_ad_client: "ca-pub-5697792530730507",
     enable_page_level_ads: true
 });
</script>
  <div style="background-color:#0E3D14;color:white;">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <div class="footer-social-icons"><a href="https://www.facebook.com/uttarakhandtravellers/" target="_blank"><i class="fa fa-facebook-square" title="uttarakhandtraveller on Facebook"></i></a> <!--a href="#" target="_blank"><i class="fa fa-twitter-square" title="eUttaranchal on Twitter"></i></a> <a href="#" target="_blank"><i class="fa fa-youtube-square" title="uttarakhandtraveller on Youtube"></i></a>  <a href="#" target="_blank"><i class="fa fa-google-plus" title="uttarakhandtraveller on Google+"></i></a></div--><a href="https://instagram.com/uttarakhandtraveller" target="_blank"><i class="fa fa-instagram" title="uttarakhandtraveller on Instagram"></i></a>
        <div class="copyright"><p>All rights reserved. &copy; <a href="http://www.uttarakhandtraveller.com">uttarakhandtraveller.com</a></p>
          <a href="{% url 'terms_and_conditions' %}" style="color:white;"><i class="fa fa-info-circle">Terms and conditions</i></a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block head_title %}Making you fall in love with Uttarakhand | {{ block.super }}{% endblock %}




{% block style %}

<link href="{% static 'css/image_hover.css' %}" rel="stylesheet">

<style>
/* Hover */
.card:hover {
  background-color:#F0F8FF;
}

.nodec{
	text-decoration: none;
}
</style>


{% include 'style.html' %}
{% endblock %}

{% block jumbotron %}

<div class="jumbotron">
	<div class="container" style="background:transparent;">
		<div class="row">
			<div class='col-sm-7 col-md-offset-5'>
				<div class="jumbotron-content"></div>
				<h1>Uttarakhand Traveller</h1>
				<p class="lead"> We make you fall in love with Uttarakhand</p>
				</div>
			</div>
		</div>
	</div>

 <div class="container">
	 <div class="row">
		<div class="text-center hidden-xs">
			<h2 style="text-decoration: underline;">Plan your visit in Uttarakhand with Uttarakhand Traveller</h2>
		</div>
		<div class="text-center visible-xs">
			<h4 style="text-decoration: underline;">Plan your visit in Uttarakhand with Uttarakhand Traveller</h4>
		</div>
		{% for place in places %}
		<div class="col-md-4">
				<div class="thumbnail card">
					<a href="{{ place.get_absolute_url }}">
						<div class="hovereffect">
							<img  src="{{ place.image.all.0.url.url }}" alt="Lights" style="height:250px;width:400px;margin-bottom:10px;">
						</div>
					</a>
					<br/>
					<div class="caption text-center">
						<h3 class="hidden-xs">{{ place.name }}</h3>
						<h4 class="visible-xs">{{ place.name }}</h4>
						<p>{{ place.description|truncatechars:150 }}</p>
					</div>
					<div class="text-center">
							<a href="{{ place.get_absolute_url }}"><button type="button" class="btn btn-primary">Explore More</button></a>
					</div>
				</div>
		
		</div>
		{% endfor %}
	</div>
   <!--  Horizontal Slider  -->
   
	<!-- Display destinations here in a set of 4 --> 
	<div class="row pad-top-30">
			<div class="text-center hidden-xs">
					<h2 style="text-decoration: underline;">Top places to visit in Uttarakhand</h2>
			</div>
			<div class="text-center visible-xs">
					<h4 style="text-decoration: underline;">Top places to visit in Uttarakhand</h4>
			</div>
			{% for spot in spots %}
			<div class="col-md-3">
				<div class="thumbnail card">
					<a href="{{ spot.get_absolute_url }}">
						<div class="hovereffect">
							<img  src="{{ spot.image.all.0.url.url }}"  alt="Lights" style="height:200px;width:400px;margin-bottom:10px;">
						</div>
					</a>
					<div class="caption text-center">
							<h3 class="hidden-xs">{{ spot.name }}</h3>
							<h4 class="visible-xs">{{ spot.name }}</h4>
						<p>{{ spot.description|truncatechars:100 }}</p>
					</div>
					<div class="text-center">
							<a href="{{ spot.get_absolute_url }}"><button type="button" class="btn btn-primary">Explore More</button></a>
					</div>	
				</div>
					
			</div>
			{% endfor %}
	</div>

	<!-- Display Temples here in a set of 4 --> 
	<div class="row pad-top-30">
			<div class="text-center hidden-xs">
					<h2 style="text-decoration: underline;">Top Temples to visit in Uttarakhand</h2>
				</div>
				<div class="text-center visible-xs">
					<h4 style="text-decoration: underline;">Top Temples to visit in Uttarakhand</h4>
				</div>
			{% for temple in temples %}
				<div class="col-md-3">
					<div class="thumbnail card">
						<a href="{{ temple.get_absolute_url }}">
							<div class="hovereffect">
								<img src="{{ temple.image.all.0.url.url }}" alt="Lights" style="height:200px;width:400px;margin-bottom:10px;">
							</div>
						</a>
						<div class="caption text-center">
							<h3 class="hidden-xs">{{ temple.name }}</h3>
							<h4 class="visible-xs">{{ temple.name }}</h4>
							<p>{{ temple.description|truncatechars:100 }}</p>
						</div>
						<div class="text-center">
								<a href="{{ temple.get_absolute_url }}"><button type="button" class="btn btn-primary">Explore More</button></a>
						</div>
					</div>
				</div>
			{% endfor %}
	</div>
 	<div class="row pad-top-30">
 		<div class="col-md-8">
 			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Top Articles in Uttarakhand Traveller Blog</h3>
				</div>
				<div class="panel-body">
					{% for post in posts%}
				    <div class="media card">
				    	<a class="pull-left" href="{{ post.get_absolute_url }}">
				    		<img class="media-object img-rounded" src="{% if post.image_url %}{{ post.image_url.url }}{% else %}{{ post.image.all.0.url }}{% endif %}" style="height:120px;width:250px;" alt="...">
				    	</a>
				    	<div class="media-body">
				    		<h4 class="media-heading">{{ post.title }}</h4>
				    		<p>{{ post.description|truncatechars:150 }}</p>
				    	</div>
						<div class="text-right">
								<a href="{{ post.get_absolute_url }}"><button type="button" class="btn btn-primary">Read More</button></a>
						</div>
					</div>
					{% endfor %}
				</div>
				<!--a class="panel-readmore" href="#">Know More</a-->
			</div>

 		</div>
 		 <!--sidebar -->
 		<div class="col-md-4">
 			<div class="list-group">
  			  <a href="{% url 'home' %}" class="list-group-item active">
  			    Home
  			  </a>
  			  <a href="{% url 'post_list' %}" class="list-group-item ">Blog</a>
  			  <!--a href="{% url 'comingsoon' %}" class="list-group-item">Places And Facts</a-->
  			  <a href="{% url 'about' %}" class="list-group-item">About</a>
  			  <a href="{% url 'contact' %}" class="list-group-item">Contact Us</a>
					<a href="{% url 'facebook_posts' %}" class="list-group-item">Facebook Posts</a>
					<a href="http://go.uttarakhandtraveller.com/upload" class="list-group-item">Upload Photos</a>
			</div>
			<h3>Top 5 Places To Visit</h3>
			<div class="grey-list-group">
				<a href = "{% url 'places:place_detail' 'nainital' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Nainital</h4>
			  <!--p class="list-group-item-text">...</p-->
				</a>
				<a href = "{% url 'places:place_detail' 'devprayag' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Devprayag</h4>
				</a>
				<a href="{% url 'places:place_detail' 'almora' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Almora</h4>
				</a>
				<a href="{% url 'places:place_detail' 'kausani' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Kausani</h4>
				</a>
				<a href="{% url 'places:place_detail' 'ranikhet' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Ranikhet</h4>
				</a>
		  </div>
 		</div>

 	</div>
 </div>
<div class="footer" >
  <footer class="fixed-bottom">
  <div class="copyright"></div>
    <p>Copyright &copy; Uttarakhand Traveller. All rights reserved.</p>
  <a href="{% url 'terms_and_conditions' %}" style="color:white;"><i class="fa fa-info-circle">Terms and conditions</i></a>
  </footer>
</div>
{% endblock %}

src/templates/home_old.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block head_title %}Making you fall in love with Uttarakhand | {{ block.super }}{% endblock %}




{% block style %}
{% include 'style.html' %}
{% endblock %}




{% block jumbotron %}

<div class="jumbotron">
	<div class="container" style="background:transparent;">
		<div class="row">
			<div class='col-sm-7 col-md-offset-5'>
				<div class="jumbotron-content"></div><br/><br/>
				<h1>Uttarakhand Traveller</h1>
				<p class="lead"> We make you fall in love with Uttarakhand.</p>
				</div>
			</div>
			<!--div class='col-sm-6' >
				<iframe width="560" height="315" src="https://www.youtube.com/embed/Z-NC987aYXI" frameborder="0" allowfullscreen></iframe>

	 		</div-->
		</div>
	</div>
 </div>


 <div class="container">
	 <div class="row">
	 {% for bp in blogpost %}
 		<div class="col-md-4">
 			<div class="bluebox">
 				<h3>{{ bp.title }}</h3>
 				<p> {{ bp.description|truncatewords:30 }}</p>
 				<a class="readmore" href="{{ bp.get_absolute_url }}"> Read More</a>
 			</div>
 		</div>
	{% endfor %}
	 </div>
 	<div class="row pad-top-30">
 		<div class="col-md-8">
 			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Places And Facts About Uttarakhand</h3>
				</div>
				<div class="panel-body">
				    <div class="media">
				    	<a class="pull-left" href="#">
				    		<img class="media-object img-rounded" src="{% static 'img/kedarkantha.jpg' %}" alt="...">
				    	</a>
				    	<div class="media-body">
				    		<h4 class="media-heading">Kedarkantha Peak</h4>
				    		<p> Kedarkantha is a mountain peak of the Himalayas in Govind Wildlife Sanctuary Uttarakhand. Its elevation is 12,500 ft.
							The climb to the peak of Kedarkantha starts from a small village called as Sankri. There are a total of 13 peaks of the Himalayan range visible from the Kedarkantha peak. </p>
				    	</div>
				    </div>

				    <div class="media">
				    	<a class="pull-left" href="#">
				    		<img class="media-object img-rounded" src="{% static 'img/rudradhari.jpg' %}" alt="...">
				    	</a>
				    	<div class="media-body">
				    		<h4 class="media-heading">Rudradhari Caves</h4>
				    		<p> udradhari caves and falls are located in Kasauni- Almore road with 12 km distance from Kasauni. People who are adventurous and willing to experience thrill and seclusion of being in a forest should definitely visit these caves and falls. There is also a small ‘Someshwar’ temple situated near by falls, devotees have strong faith and spiritual connection with this temple.</p>
				    	</div>
				    </div>

				    <div class="media">
				    	<a class="pull-left" href="#">
				    		<img class="media-object img-rounded" src="{% static 'img/Chaukhamba.jpg' %}" alt="...">
				    	</a>
				    	<div class="media-body">
				    		<h4 class="media-heading">Chaukhamba</h4>
				    		<p> Chaukhamba Viewpoint is a mesmerizing place which offers to its visitors captivating panoramas of beautiful Idwal valley. Situated 4km from Pauri, one can witness the spellbinding glaciers, the source of water for River Ganga.
							The thick cover of rhododendron and oak forest is the major attraction of the place.</p>
				    	</div>
				    </div>
				</div>
				<!--a class="panel-readmore" href="#">Know More</a-->
			</div>

 		</div>
 		 <!--sidebar -->
 		<div class="col-md-4">
 			<div class="list-group">
  			  <a href="{% url 'home' %}" class="list-group-item active">
  			    Home
  			  </a>
  			  <a href="{% url 'post_list' %}" class="list-group-item ">Blog</a>
  			  <!--a href="{% url 'comingsoon' %}" class="list-group-item">Places And Facts</a-->
  			  <a href="{% url 'about' %}" class="list-group-item">About</a>
  			  <a href="{% url 'contact' %}" class="list-group-item">Contact Us</a>
					<a href="{% url 'facebook_posts' %}" class="list-group-item">Facebook Posts</a>
					<a href="http://go.uttarakhandtraveller.com/upload" class="list-group-item">Upload Photos</a>
			</div>
			<h3>Top 5 Places To Visit</h3>
			<div class="grey-list-group">
				<a href = "{% url 'places:place_detail' 'nainital' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Nainital</h4>
			  <!--p class="list-group-item-text">...</p-->
				</a>
				<a href = "{% url 'places:place_detail' 'devprayag' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Devprayag</h4>
				</a>
				<a href="{% url 'places:place_detail' 'almora' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Almora</h4>
				</a>
				<a href="{% url 'places:place_detail' 'kausani' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Kausani</h4>
				</a>
				<a href="{% url 'places:place_detail' 'ranikhet' %}" class="list-group-item">
			  <h4 class="list-group-item-heading">Ranikhet</h4>
				</a>
		  </div>
 		</div>

 	</div>
 </div>
<div class="footer" >
  <footer class="fixed-bottom">
  <div class="copyright"></div>
    <p>Copyright &copy; Uttarakhand Traveller. All rights reserved.</p>
  <a href="{% url 'terms_and_conditions' %}" style="color:white;"><i class="fa fa-info-circle">Terms and conditions</i></a>
  </footer>
</div>
{% endblock %}

src/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

src/templates/navbar.html
   {% load staticfiles %}

   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color:#1A5F23;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}" style="color:white;">Uttarakhand Traveller</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a  href="{% url 'home' %}" >Home</a></li>
            <li><a href="{% url 'post_list' %}">Blog</a></li>
            <!--li><a href="{% url 'comingsoon' %}">Places & Facts</a></li-->

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Places <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'places:district_places' 'almora' %}">Almora</a></li>
                  <li><a href="{% url 'places:district_places' 'bageshwar' %}">Bageshwar</a></li>
                  <li><a href="{% url 'places:district_places' 'chamoli' %}">Chamoli</a></li>
                  <li><a href="{% url 'places:district_places' 'champawat' %}">Champawat</a></li>
                  <li><a href="{% url 'places:district_places' 'dehradun' %}">Dehradun</a></li>
                  <li><a href="{% url 'places:district_places' 'haridwar' %}">Haridwar</a></li>
                  <li><a href="{% url 'places:district_places' 'nainital' %}">Nainital</a></li>
                  <li><a href="{% url 'places:district_places' 'pauri-garhwal' %}">Pauri Garhwal</a></li>
                  <li><a href="{% url 'places:district_places' 'pithoragarh' %}">Pithoragarh</a></li>
                  <li><a href="{% url 'places:district_places' 'rudraprayag' %}">Rudraprayag</a></li>
                  <li><a href="{% url 'places:district_places' 'tehri-garhwal' %}">Tehri Garhwal</a></li>
                  <li><a href="{% url 'places:district_places' 'uttarkashi' %}">Uttarkashi</a></li>
                  <li><a href="{% url 'places:district_places' 'udham-singh-nagar' %}">Udham Singh Nagar</a></li>
                </ul>
              </li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            <li><a href="{% url 'facebook_posts' %}">Facebook Posts</a></li>
            <li><a href="http://go.uttarakhandtraveller.com/upload">Upload Photos</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right social">
                <li><a href="https://www.facebook.com/uttarakhandtravellers/"><i class="fa fa-lg fa-facebook"></i></a></li>
                <li><a href="https://www.instagram.com/uttarakhandtraveller/"><i class="fa fa-lg fa-instagram"></i></a></li>
          </ul>
      </div>
      </div>
    </nav>